docs: update EOL date
loopbackio/loopback-datasource-juggler pull request #2180
Opened 2024-01-11 19:51 UTC by dhmlau

According to the LTS schedule for Node.js https://github.com/nodejs/Release, the EOL date for Node.js 20 is 2026-04-30. So we're updating the EOL date for this module accordingly. 

## Checklist

- [x] [Sign off your commits](https://loopback.io/doc/en/contrib/code-contrib.html) with DCO (Developer Certificate of Origin)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

2024-01-12 08:02 UTC, samarpanB requested changes

2024-01-12 08:02 UTC, samarpanB commented on README.md
> +| 4.x        | Current         | Oct 2018  | Apr 2026 _(minimum)_ |
But juggler version is already 5.x

2024-01-12 21:14 UTC, dhmlau commented on README.md
> +| 4.x        | Current         | Oct 2018  | Apr 2026 _(minimum)_ |
good catch. I've updated accordingly.

2024-01-13 03:05 UTC, achrinza approved these changes

2024-02-12 08:47 UTC, samarpanB commented on README.md
> +| 4.x        | Active          | Oct 2018  | Apr 2025             |
Are we gonna support 4.x still ?

2024-02-12 08:48 UTC, samarpanB commented on README.md
> +| 4.x        | Active          | Oct 2018  | Apr 2025             |
4.x is on noidejs 16

2024-07-11 09:16 UTC, samarpanB approved these changes

2024-07-11 09:17 UTC, merged